### ISSUE TITLE
Is it possible to randomly traverse the IPV6 address space？

### ISSUE THREAD

**Issue by chushuai** [dadrian/ziterate-go#1]
I want to randomly traverse integers in the range 2^128 , How should I set the group 
https://github.com/dadrian/ziterate-go/blob/adc489b59ca0324331b5d374ade6cefb4e328191/groups.go#L5

**Comment by dadrian** [comment]
You'd have to define a group where P is prime and greater than 2^128.

Realistically, this is not a possible iteration to complete any non-negligible percentage of in any reasonable amount of time.

**Comment by chushuai** [comment]
I am confused how to generate KnownRoot、OrderFactors，Whether it can automatically generate P、KnownRoot、OrderFactors according to the input size。

**Comment by dadrian** [comment]
> I am confused how to generate KnownRoot、OrderFactors

Order factors are the prime factorization of `P - 1`. `KnownRoot` is a generator `g` of the multiplicative group of order `P-1` (Z/pZ).

To calculate `KnownRoot`, find a `g` such that for all `x` in `OrderFactors`, `g^x mod P != 1` and `g^{P-1} = 1`.

There's not a fast algorithm for factoring a number, so this is not done automatically. For more details, see https://en.wikipedia.org/wiki/Cyclic_group and https://math.stackexchange.com/questions/814879/find-a-generator-of-the-multiplicative-group-of-mathbbz-23-mathbbz-as-a-c and Section 2.1 of https://zmap.io/paper.pdf
